shenyangHuang/openDG

- .pre-commit-config.yaml
Close https://github.com/shenyangHuang/openDG/issues/18
> Exclude test dir from mypy git hook

- opendg/_storage/backends/__init__.py
- opendg/_storage/backends/array_backend.py
- opendg/_storage/backends/dict_backend.py
- opendg/_storage/base.py
- opendg/graph.py
- test/test_dgraph.py
- test/test_storage_impl.py
> `DGraph` view over `DGStorage`

- opendg/nn/__init__.py
- opendg/nn/memory/__init__.py
- opendg/nn/memory/edgebank.py
- test/test_model/test_edgebank.py
- added Edgebank in `nn/memory/edgebank.py`
- added simple test example for edgebank
> Adding EdgeBank with simple test set 

- opendg/_io/__init__.py
- opendg/_io/csv.py
- opendg/graph.py
- test/test_dgraph.py
- test/test_io/test_csv_io.py
> Simplify io interface

- opendg/_storage/backends/array_backend.py
- opendg/_storage/base.py
- opendg/graph.py
- opendg/loader/base.py
- test/test_dgraph.py
- test/test_loader/test_dg_loader.py
- test/test_storage_impl.py
> Add materialize implementation

- .github/workflows/ruff.yml
- opendg/nn/memory/edgebank.py
- opendg/perf/__init__.py
- opendg/util/perf.py
- opendg/util/seed.py
- perf/foo.py
- pyproject.toml
- test/test_util/test_seed.py
- uv.lock
> Add basic perf utils

- opendg/graph.py
- test/test_dgraph.py
> Add node property to `DGraph`

- opendg/_storage/backends/array_backend.py
- opendg/_storage/base.py
- opendg/graph.py
- test/test_storage_impl.py
> Get num edges from DGraph

- opendg/nn/__init__.py
- opendg/nn/time_encoding.py
- test/test_model/test_time2vec.py
> Add time2vec

- opendg/_io/__init__.py
- opendg/_io/tgb.py
- pyproject.toml
- test/test_io/test_tgb_io.py
- uv.lock
Add the support for the TGB linkproppred to the IO, we could also add tgb/nodeproppred down the line.
> Add TGB IO

- opendg/loader/neighbor_loader.py
- test/test_loader/test_neighbor_loader.py
> Fix NeighborLoader Batch Time

- opendg/_storage/backends/array_backend.py
- opendg/_storage/base.py
- opendg/graph.py
- test/test_dgraph.py
> Node/Edge Feat Dim Getter

- opendg/nn/memory/edgebank.py
- test/test_model/test_edgebank.py
> EdgeBank nn.Module API

- opendg/graph.py
- test/test_dgraph.py
- test/test_loader/test_dataloader.py
> Make DGBatch a dataclass

- examples/edgebank.py
> EdgeBank Example

- examples/tgat.py
> `TGAT` example

- opendg/_storage/__init__.py
- opendg/_storage/backends/array_backend.py
- opendg/_storage/base.py
- opendg/graph.py
- opendg/loader/neighbor_loader.py
- test/test_storage_impl.py
> Pass slicetracker to storage

- opendg/_storage/backends/array_backend.py
- opendg/_storage/base.py
> Simplify feature dim check

- opendg/_storage/backends/array_backend.py
- opendg/_storage/base.py
- opendg/graph.py
- test/test_dgraph.py
- test/test_storage_impl.py
> Add num_events property

- opendg/loader/base.py
- test/test_loader/test_dataloader.py
- test/test_loader/test_neighbor_loader.py
> Fix Event Iteration

- LICENSE
- README.md
> Add mit license

- opendg/_io/csv.py
- opendg/_io/pandas.py
- opendg/_io/tgb.py
- opendg/events.py
- test/test_events.py
- test/test_io/test_csv_io.py
- test/test_io/test_pandas_io.py
- test/test_io/test_tgb_io.py
> Add global idx to events

- opendg/graph.py
- opendg/loader/dataloader.py
- test/test_loader/test_dataloader.py
- test/test_loader/test_neighbor_loader.py
> Force materialize and writeable dbatch

- examples/tgat.py
- opendg/hooks.py
- test/test_hooks/test_negative_edge_sampler_hook.py
- test/test_hooks/test_neighbor_sampler_hook.py
> Fix TGAT Hook Run

- opendg/hooks.py
> Tensor output for recency hook

- examples/gcn.py
- opendg/_io/__init__.py
- opendg/_io/tgb.py
- opendg/graph.py
instead of adding time coarsen function, I believe currently loading by time granularity is sufficent enough for any discretization research need. Instead, I added added time granularity for `tgbl-wiki` and `tgbl-review` now.
> adding time granularity to tgb datasets

- examples/edgebank.py
- examples/gclstm.py
- examples/gcn.py
- examples/tgat.py
- opendg/graph.py
> Fix TimeDelta Default Argument TGB Logic

- pyproject.toml
- uv.lock
> Pin TGB dependancy to master

- examples/tgat.py
- jobs/configs/methods.txt
- jobs/scripts/run_method.sh
- jobs/scripts/submit_all.sh
> TGAT Experiments

- examples/gcn.py
- jobs/configs/methods.txt
- jobs/scripts/run_method.sh
- jobs/scripts/submit_all.sh
> GCN Experiments

- examples/gclstm.py
- jobs/configs/methods.txt
- jobs/scripts/run_method.sh
- jobs/scripts/submit_all.sh
> GCLSTM Experiments

- docs/data.md
- mkdocs.yml
- opendg/data.py
- test/test_data.py
> Add DGData Object

- examples/gclstm.py
- examples/gcn.py
- examples/tgat.py
- examples/tgn.py
- opendg/graph.py
- opendg/hooks.py
- test/test_dgraph.py
- test/test_hooks/test_hook_manager.py
> Add Device Semantics to DGraph
